name: Worklflow-Testing

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Kommentar hinzufügen
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            event: 'COMMENT',
            body: 'Hello World!'
          })

