name: AI-gestützte Codeanalyse

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Run GPT-4 Analysis
      uses: actions/github-script@v5
      with:
        script: |
          const openai = require('openai');
          openai.apiKey = process.env.API_Key;

          // Beispiel, um GPT-4 mit Pull Request Daten zu füttern
          const response = await openai.createCompletion({
            model: 'GPT-4', // Ersetzen Sie dies mit dem aktuellen GPT-4 Modell
            prompt: 'Analyse this code: ' + codeSnippet, // Setzen Sie hier Ihren Code oder die PR-Beschreibung ein
            temperature: 0.7,
            max_tokens: 150,
          });

          // Kommentar mit GPT-4 Analyse hinzufügen
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: response.data.choices[0].text,
          });
