name: AI Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        npm install @octokit/rest openai
      env:
        NODE_VERSION: '14'
        
    - name: Analyze PR and commits
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.API_Key }}
      run: node analyze-pr.js
