name: AI Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # oder eine andere Version Ihrer Wahl
    - name: Install dependencies
      run: |
        npm install @octokit/rest openai
        npm install openai@latest
      env:
        NODE_VERSION: '14'
        
    - name: Analyze PR and commits
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: node analyze-pr.js
