name: Analyze PR with ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Analyze PR content and comment using ChatGPT
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prTitle = context.payload.pull_request.title;
            const prBody = context.payload.pull_request.body;
            const prContent = `Please summarize the following Pull Request content:\nTitle: ${prTitle}\n\nDescription: ${prBody}`;

            const response = await fetch('https://api.openai.com/v1/completions', {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                model: 'text-davinci-003', // Adjust based on the model you're using
                prompt: prContent,
                max_tokens: 150,
                temperature: 0.7
              })
            });

            const data = await response.json();

            const summary = data.choices[0].text.trim();

            // Post the summary as a comment on the PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `## ChatGPT Summary\n\n${summary}`
            });
