name: Echo PR Details

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  echo-pr-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo PR Content
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prTitle = context.payload.pull_request.title;
            const prBody = context.payload.pull_request.body;
            // Konstruiere die Nachricht, die gepostet werden soll
            const message = `
              ## Pull Request Details\n
              **Title:** ${prTitle}\n
              **Description:**\n
              ${prBody}
            `;
            // Poste die Nachricht als Kommentar zum PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message
            });
