name: Analyze PR with ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Analyze PR content and comment using ChatGPT
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { HttpClient, HttpHeaders } = require('@actions/http-client');
            const http = new HttpClient('github-script');
            const prTitle = context.payload.pull_request.title;
            const prBody = context.payload.pull_request.body;
            const prContent = `Please summarize the following Pull Request content:\nTitle: ${prTitle}\n\nDescription: ${prBody}`;

            const openAIResponse = await http.postJson(
              'https://api.openai.com/v1/completions',
              {
                model: 'GPT-4', // Adjust the model name based on the actual available version
                prompt: prContent,
                max_tokens: 150, // Adjust based on how detailed you want the response to be
                temperature: 0.7
              },
              {
                headers: new HttpHeaders({
                  'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
                  'Content-Type': 'application/json'
                })
              }
            );

            const summary = openAIResponse.result.choices[0].text.trim();

            // Post the summary as a comment on the PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `## ChatGPT Summary\n\n${summary}`
            });
